### ISSUE TITLE
[C14877] object null is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by seveibar** [tscircuit/easyeda-converter#53]

**Comment by andrii-balitskyi** [comment]
@seveibar `tsx cli/main.ts convert -i C14877 --output-format tsx` seems to be working fine for me
![Image](https://github.com/user-attachments/assets/6d18f6fe-0a93-401c-a7fb-7f4bc342bbad)

**Comment by seveibar** [comment]
@andrii-balitskyi i think i fixed this one when i fixed a different issue- thanks for confirming!

**Comment by seveibar** [comment]
@andrii-balitskyi also there is now a script in the scripts directory to automatically download and generate a test for a part number- it's pretty cool!

**Comment by andrii-balitskyi** [comment]
@seveibar, that's awesome! Thanks for creating the script!
